### ISSUE TITLE
Broken on Fabric Loader 0.12.0+ (and 1.18+)

### ISSUE THREAD

**Issue by wafflecoffee** [comp500/mixintrace#5]
A crash on loader 0.12.1: https://hastebin.com/isixedepes.yaml
Same crash on loader 0.11.7: https://hastebin.com/axomarowit.yaml

See https://fabricmc.net/2021/10/03/loader-0120.html#mixin-compatibility for more info on what exactly changed in loader in regards to 0.12.

**Comment by comp500** [comment]
I should probably have linked this earlier: https://github.com/SpongePowered/Mixin/pull/529 will make it possible to fix this issue (should I PR it to Fabric's fork too?)

**Comment by sudofox** [comment]
Finally updating my installed mods to 1.18.2 , is this still blocked?

**Comment by srnyx** [comment]
Minecraft is now on 1.19, any plans on updating this?
