### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [comp500/mixintrace#6]
Port the mod to 1.12.2

**Comment by comp500** [comment]
No, [1.12.2](https://howoldisminecraft1122.today/) is unsupported by all major modloaders.

**Comment by Kasia1403** [comment]
What ?! How 1.12.2 could be unsupported ? It has MOST mods ! For example Dr. Zhark's Mo' Creatures is for 1.12.2 and not for 1.13+ ! I don't want to play without Mo' Creatures !
