### ISSUE TITLE
Show mixins in the log not just the crash report

### ISSUE THREAD

**Issue by rayzchen** [comp500/mixintrace#8]
Sometimes a mod will crash but recover itself, while an exception is printed to the log. Could you add a feature to print the mixin class there?

![image](https://user-images.githubusercontent.com/54078384/185603213-f7927489-ea26-457e-b111-7cd1c9cd1c91.png)

**Comment by comp500** [comment]
I don't think this is really feasible, as I can't hook every place where `printStackTrace` or similar JVM functions are called; interoperability would have to be written for every single mod that prints exceptions to the log.

**Comment by rayzchen** [comment]
When does this actually trigger? I'm having trouble actually getting a crash report, as sometimes in the log Minecraft says it crashed but no crash report was generated.

**Comment by comp500** [comment]
It triggers whenever a crash report is generated; when you see the `---- Minecraft Crash Report ----` heading. I think this is usually shown in the launcher's game log (I suggest using PolyMC/MultiMC/ATLauncher, the vanilla launcher doesn't always show the actual crash log) as well as a file in the `crash-reports` folder.

**Comment by rayzchen** [comment]
What I’m trying to say is sometimes the crash report isn’t generated at all...

**Comment by rayzchen** [comment]
Can minecraft crash without generating a crash report?

**Comment by comp500** [comment]
Yes, though it's uncommon since most Minecraft code paths catch exceptions and generate a crash report.
